/* Generated by pascal2c – source: Fibonacci */
#include "pascal_runtime.h"

int n;
int i;
int a;
int b;
int tmp;

int main(void)
{
    n = 10;
    {
        printf("%s", "First 10 Fibonacci numbers:");
        printf("\n");
    }
    a = 0;
    b = 1;
    for (i = 1; i <= n; ++i)
        {
            {
                printf("%d", a);
                printf("\n");
            }
            tmp = (a + b);
            a = b;
            b = tmp;
        }
    return 0;
}
